# Generated by Django 6.0.2 on 2026-03-17 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_lite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='crm_lite.company', verbose_name='Компания'),
        ),
    ]
