# Generated by Django 6.0.2 on 2026-03-22 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_lite', '0002_alter_storage_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='INN',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Закупочная стоимость')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('storage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm_lite.storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INN', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('title', models.CharField(max_length=255, verbose_name='Название поставщика')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='crm_lite.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата доставки')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='crm_lite.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='SupplyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_lite.product', verbose_name='Товар')),
                ('supply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_lite.supply', verbose_name='ID поставки')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplies',
            field=models.ManyToManyField(through='crm_lite.SupplyProduct', to='crm_lite.supply'),
        ),
        migrations.AddConstraint(
            model_name='supplyproduct',
            constraint=models.UniqueConstraint(fields=('supply_id', 'product_id'), name='unique_product_supply'),
        ),
    ]
