# Generated by Django 6.0.2 on 2026-03-26 13:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_lite', '0003_alter_company_inn_alter_storage_address_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Закупочная стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplies',
            field=models.ManyToManyField(related_name='products', through='crm_lite.SupplyProduct', to='crm_lite.supply'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование поставщика'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки'),
        ),
        migrations.AlterField(
            model_name='supplyproduct',
            name='supply_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_products', to='crm_lite.supply', verbose_name='ID поставки'),
        ),
    ]
