# Generated by Django 6.0.2 on 2026-04-03 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_lite', '0004_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyproduct',
            options={'verbose_name': 'Товар в поставке', 'verbose_name_plural': 'Товары в поставке'},
        ),
        migrations.AlterField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата поставки'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50, verbose_name='Имя покупателя')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата продажи')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm_lite.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_lite.product', verbose_name='Товар')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='crm_lite.sale', verbose_name='ID продажи')),
            ],
            options={
                'verbose_name': 'Товар из продажи',
                'verbose_name_plural': 'Товары из продажи',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.ManyToManyField(related_name='products', through='crm_lite.ProductSale', to='crm_lite.sale'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.UniqueConstraint(fields=('sale_id', 'product_id'), name='unique_product_sale'),
        ),
    ]
